### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by javier500** [SAP/lumira-extension-da-httpaccess#1]
Hi,I get "Acquisition fail" when I select httpacces-dae-lumira. My version of Lumira is 1.25.1

**Comment by vamsi-id** [comment]
Could you please try using the new executable I've updated today? Are you able to get a proper response when you make the same call through the browser? More details on the request you are sending will be helpful.

**Comment by javier500** [comment]
Hi Vamsiraju!
Thank you very much. With the new version, it works!
